# Generated by Django 3.0 on 2021-01-21 07:53

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='gridMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_en', models.IntegerField(default=0)),
                ('lng_en', models.IntegerField(default=0)),
                ('lat_ws', models.IntegerField(default=0)),
                ('lng_ws', models.IntegerField(default=0)),
                ('lat_c', models.IntegerField(default=0)),
                ('lng_c', models.IntegerField(default=0)),
                ('datetime_start', models.DateTimeField(default=datetime.datetime(2021, 1, 21, 14, 53, 45, 915092))),
                ('datetime_end', models.DateTimeField(default=datetime.datetime(2021, 1, 22, 14, 53, 45, 915092))),
            ],
        ),
        migrations.CreateModel(
            name='Heatmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_en', models.IntegerField(default=0)),
                ('lng_en', models.IntegerField(default=0)),
                ('lat_ws', models.IntegerField(default=0)),
                ('lng_ws', models.IntegerField(default=0)),
                ('datetime_start', models.DateTimeField(default=datetime.datetime(2021, 1, 21, 14, 53, 45, 915092))),
                ('datetime_end', models.DateTimeField(default=datetime.datetime(2021, 1, 22, 14, 53, 45, 915092))),
            ],
        ),
    ]
