# Generated by Django 3.0 on 2021-02-04 15:34

import datetime
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='gridMap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_en', models.IntegerField(default=0)),
                ('lng_en', models.IntegerField(default=0)),
                ('lat_ws', models.IntegerField(default=0)),
                ('lng_ws', models.IntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='Heatmap',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_en', models.IntegerField(default=0)),
                ('lng_en', models.IntegerField(default=0)),
                ('lat_ws', models.IntegerField(default=0)),
                ('lng_ws', models.IntegerField(default=0)),
                ('date_start', models.DateField(default=datetime.datetime(2019, 1, 1, 0, 0))),
                ('date_end', models.DateField(default=datetime.datetime(2019, 1, 2, 0, 0))),
            ],
        ),
        migrations.CreateModel(
            name='login_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('password', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='signup_model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(blank=True, max_length=250, null=True)),
                ('email', models.EmailField(max_length=255, unique=True, verbose_name='email address')),
                ('password', models.CharField(blank=True, max_length=250, null=True)),
                ('confirm_password', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='tourist_place_detail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lat_en', models.IntegerField(default=0)),
                ('lng_en', models.IntegerField(default=0)),
                ('lat_ws', models.IntegerField(default=0)),
                ('lng_ws', models.IntegerField(default=0)),
                ('date_start', models.DateField(default=datetime.datetime(2019, 1, 1, 0, 0))),
                ('date_end', models.DateField(default=datetime.datetime(2019, 1, 2, 0, 0))),
            ],
        ),
        migrations.CreateModel(
            name='trip_detail_analysis',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_start', models.DateField(default=datetime.datetime(2019, 1, 1, 0, 0))),
                ('date_end', models.DateField(default=datetime.datetime(2019, 1, 2, 0, 0))),
                ('hotal_id', models.CharField(blank=True, max_length=100, null=True)),
                ('trip_data', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='trip_title_api',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.IntegerField(default=0)),
                ('trip_name', models.CharField(blank=True, max_length=100, null=True)),
                ('date_start', models.DateField(default=datetime.datetime(2019, 1, 1, 0, 0))),
                ('date_end', models.DateField(default=datetime.datetime(2019, 1, 2, 0, 0))),
                ('hotal_id', models.CharField(blank=True, max_length=100, null=True)),
                ('trip_data', models.TextField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='trip_titles',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('trip_name', models.CharField(blank=True, max_length=250, null=True)),
                ('city_code', models.CharField(blank=True, max_length=250, null=True)),
                ('start_trip_date', models.DateField(default=datetime.datetime(2019, 1, 1, 0, 0))),
                ('end_trip_date', models.DateField(default=datetime.datetime(2019, 1, 2, 0, 0))),
                ('hotel_id', models.CharField(blank=True, max_length=250, null=True)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='trip_details',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('datetime_start', models.DateField(default=datetime.datetime(2019, 1, 1, 9, 0))),
                ('datetime_end', models.DateField(default=datetime.datetime(2019, 1, 1, 12, 0))),
                ('poi', models.CharField(blank=True, max_length=250, null=True)),
                ('place_name', models.CharField(blank=True, max_length=250, null=True)),
                ('lat', models.IntegerField(default=0)),
                ('lng', models.IntegerField(default=0)),
                ('last_updated', models.DateTimeField(auto_now=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('trip_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='app.trip_titles')),
            ],
        ),
    ]
