# Generated by Django 3.0 on 2021-02-06 04:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='car_stop_data',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(blank=True, max_length=250, null=True)),
                ('lat', models.IntegerField(default=0)),
                ('lon', models.IntegerField(default=0)),
                ('stop_time', models.IntegerField(default=0)),
                ('time_stamp', models.DateTimeField(default=datetime.datetime(2019, 1, 1, 9, 0))),
                ('vid', models.CharField(blank=True, max_length=250, null=True)),
                ('pname', models.CharField(blank=True, max_length=250, null=True)),
            ],
        ),
    ]
