# Generated by Django 3.0 on 2021-01-21 07:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridmap',
            name='datetime_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 22, 14, 54, 26, 127419)),
        ),
        migrations.AlterField(
            model_name='gridmap',
            name='datetime_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 21, 14, 54, 26, 127419)),
        ),
        migrations.AlterField(
            model_name='heatmap',
            name='datetime_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 22, 14, 54, 26, 127419)),
        ),
        migrations.AlterField(
            model_name='heatmap',
            name='datetime_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 21, 14, 54, 26, 127419)),
        ),
    ]
