# Generated by Django 3.0 on 2021-02-06 07:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0002_car_stop_data'),
    ]

    operations = [
        migrations.DeleteModel(
            name='car_stop_data',
        ),
    ]
