# Generated by Django 3.0 on 2021-01-21 13:57

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_auto_20210121_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gridmap',
            name='datetime_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 22, 20, 57, 27, 741303)),
        ),
        migrations.AlterField(
            model_name='gridmap',
            name='datetime_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 21, 20, 57, 27, 741303)),
        ),
        migrations.AlterField(
            model_name='heatmap',
            name='datetime_end',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 22, 20, 57, 27, 741303)),
        ),
        migrations.AlterField(
            model_name='heatmap',
            name='datetime_start',
            field=models.DateTimeField(default=datetime.datetime(2021, 1, 21, 20, 57, 27, 741303)),
        ),
    ]
