# Generated by Django 3.0 on 2021-02-07 08:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('app', '0003_delete_car_stop_data'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='trip_titles',
            name='user',
        ),
        migrations.RenameField(
            model_name='trip_title_api',
            old_name='date_end',
            new_name='end_trip_date',
        ),
        migrations.RenameField(
            model_name='trip_title_api',
            old_name='hotal_id',
            new_name='hotel_id',
        ),
        migrations.RenameField(
            model_name='trip_title_api',
            old_name='date_start',
            new_name='start_trip_date',
        ),
        migrations.AddField(
            model_name='trip_title_api',
            name='city_code',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
        migrations.AddField(
            model_name='trip_title_api',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='trip_title_api',
            name='last_updated',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.DeleteModel(
            name='trip_details',
        ),
        migrations.DeleteModel(
            name='trip_titles',
        ),
    ]
